# Site settings
title: qiiq blog 
header-img: img/home-bg.jpg
email: qiiqadmin@qiiq.co.in
description: "Explore, learn, enjoy."
baseurl: ""
url: "http://qiiqer.github.io"
twitter_username: ""
github_username: qiiqadmin 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
